org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

kotlin.code.style=official

# 沙箱/CI 环境无外网，禁止 AGP 自动联网下载 SDK 组件
android.builder.sdkDownload=false

android.suppressUnsupportedCompileSdk=37.0
